
print("Jech Azlie S. Rivera")
print("50")
print("18 years old")
print("50")
print("Brgy. Cochero, Iloilo City")
print("100")
print("female")
print("100")
print("Rossana C. Salva")
print("100")
print("45 years old")
print("100")
print("Overseas Filipino Worker")
print("100")
print("Jr B. Rivera")
print("100")
print("39 years old")
print("100")
print("Political Driver")
print("100")